#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

dind &

ATTEMPTS=0
while [ $ATTEMPTS -lt 10 ]; do
  docker version &> /dev/null
  if [ $? -eq 0 ]; then
    break
  fi

  let ATTEMPTS=ATTEMPTS+1
  sleep 1
done

set -x
eval "$@"
set +x

kill $(cat /var/run/docker.pid)
